### PR TITLE
Issues #42 - Get a region by name + country

### PR DESCRIPTION
**Pull request by z0rr0**
Hi,
Could you please check this pull request?
It should help to resolve the problem of updating Cities if there are Regions with duplicate names, but different country codes.

### CODE REVIEW

**Comment by z0rr0** [comment]
Please don't apply this request. It results to KeyError for a new database synchronization. Some cities are in cidr_optim.txt, but not in cities.txt. So, city->country mapping doesn't work.

**Comment by z0rr0** [comment]
I suggest to skip cities, if we can't find their regions.

**Comment by coagulant** [comment]
Can you add a new testcase for this bug?

**Comment by z0rr0** [comment]
Hi,
Unfortunately, I don't have much time. What tests do you want to add?

**Comment by coagulant** [comment]
It's a good practice to add regression tests to make sure this bug won't appear again if someone refactors the code later on. 

Anyway, merging this, looks ok to me

**Comment by coagulant** [comment]
We released 0.5.2 version with this fix

**Pull request merged**
